name: Update Google Sheet

on:
  schedule:
    - cron: '0 7 * * *'  # Runs daily at 07:00 UTC
  workflow_dispatch:  # Allows manual run

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create credentials file
      run: |
        echo "${{ secrets.creds }}" > creds.json

    - name: Run Python script
      run: python app.py
